# Generated by Django 3.1.2 on 2020-10-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombre_de_usuario', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
