# Generated by Django 3.1.2 on 2020-10-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productotienda',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
