# Generated by Django 3.1.2 on 2020-10-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20201023_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoTienda',
        ),
    ]
