# Generated by Django 3.1.2 on 2020-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_delete_productotienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
