# Generated by Django 3.1.2 on 2020-10-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20201024_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tienda',
        ),
    ]
